apiVersion: v1
kind: Sevice
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
    - port: 80
      tatgePort: 80
  type: LoadBalancer

---

apiVersion: v1
kend: Service
metadata:
  name: mysql-connection
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None